development:
  adapter: postgresql
  encoding: unicode
  database: geomarks
  username: geouser
  password: geopassword
  host: 127.0.0.1 
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: <%= ENV["DB_NAME"] %> 
  pool: 5
  username: <%= ENV["DB_USER"] %> 
  password: <%= ENV["DB_PASS"] %>
  host: <%= ENV["DB_HOST"] %>
  port: 5432

test: &test
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: geomarks_test
  pool: 5
  username: geouser 
  password: geopassword